### ISSUE TITLE
Gradle Plugin version 7.3.0 support

### ISSUE THREAD

**Issue by KoheiYamamoto001208** [shogo82148/gradle-android-ribbonizer-plugin#63]
If you upgrade the Android Gradle Plugin version to 7.3.0 or later, the ribbon will no longer be displayed.
Thank you in advance for your support!

**Comment by shogo82148** [comment]
Unfortunately, AGP7.x lacks the API and cannot be made to work properly.
We recommend updating to AGP8.0.

- https://github.com/shogo82148/gradle-android-ribbonizer-plugin/pull/75
- https://github.com/shogo82148/gradle-android-ribbonizer-plugin/releases/tag/v8.0.0
